on: [push]
name: build
jobs:
  runhaskell:
    name: Haskell stack test
    runs-on: ubuntu-latest # or macOS-latest, or windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1.1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        with:
          ghc-version: 'latest'
          # cabal-version: 'latest'. Omitted, but defalts to 'latest'
          enable-stack: true
          stack-version: 'latest'
      - run: stack test
